# Generated by Django 3.1.2 on 2020-11-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAllergyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy1', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy2', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy3', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy4', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy5', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Environmental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eallergy1', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity1', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy2', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity2', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy3', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity3', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy4', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity4', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy5', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity5', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
