# Generated by Django 3.1.2 on 2020-11-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy1', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy2', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy3', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy4', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
                ('allergy5', models.CharField(choices=[('none', 'None'), ('dairy', 'Dairy'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('shellfish', 'Shellfish'), ('nuts', 'Nuts')], default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Environmental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eallergy1', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity1', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy2', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity2', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy3', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity3', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy4', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity4', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
                ('eallergy5', models.CharField(choices=[('none', 'None'), ('grass', 'Grass'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('pet dander', 'Pet Dander'), ('mold', 'Mold'), ('insect bites', 'Insect Bites')], default='None', max_length=20)),
                ('severity5', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('deadly', 'Deadly')], default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OtherAllergyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction1', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('toxic', 'Toxic')], default='None', max_length=20)),
                ('reaction2', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('toxic', 'Toxic')], default='None', max_length=20)),
                ('reaction3', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('toxic', 'Toxic')], default='None', max_length=20)),
                ('reaction4', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('toxic', 'Toxic')], default='None', max_length=20)),
                ('reaction5', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('toxic', 'Toxic')], default='None', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
