# Generated by Django 3.1.2 on 2020-11-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergy',
            new_name='FoodAllergy',
        ),
    ]
