# Generated by Django 3.1.2 on 2020-11-03 06:12

from django.db import migrations, models
import myusers.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_environmental_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmental',
            name='user',
            field=models.CharField(default='None', max_length=100, verbose_name=myusers.models.Profile),
        ),
    ]
