# Generated by Django 3.1.2 on 2020-11-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20201103_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmental',
            name='user',
        ),
    ]
