# Generated by Django 3.1.2 on 2020-10-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0002_auto_20201028_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
