# Generated by Django 3.1.2 on 2020-10-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0004_auto_20201028_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
