# Generated by Django 3.1.2 on 2020-10-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0005_auto_20201028_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegDemographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
