# Generated by Django 3.1.2 on 2020-10-29 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0006_userregdemographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregdemographics',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userregdemographics',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='userregdemographics',
            name='my_referral',
            field=models.CharField(default='The Internet', max_length=100),
        ),
        migrations.AddField(
            model_name='userregdemographics',
            name='my_weight',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
