# Generated by Django 3.1.2 on 2020-11-03 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myusers', '0007_auto_20201029_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregdemographics',
            name='user',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
